title: GitHub Pages documentation rocks! Not!
author: kingolego
description: > # this means to ignore newlines until "baseurl:"
 GitHub Pages rocks, but the documentation needs to be updated....
  
theme: minima

# social links
github_username:  kingolego # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
